### ISSUE TITLE
Elastic search 1.4.2 data path issue

### ISSUE THREAD

**Issue by dobariya** [elasticsearch/elasticsearch-cloud-aws#161]
I am using UNC path to store the data eg: \\pc1\data.
This works perfect in version 1.3.4 but after I upgrade it to 1.3.7 or 1.4.2 it started give me error  
Below is the error log

[2015-01-12 16:03:33,087][INFO ][node                     ] [master1] version[1.3.7], pid[7068], build[3042293/2014-12-16T13:59:32Z]
[2015-01-12 16:03:33,087][INFO ][node                     ] [master1] initializing ...
[2015-01-12 16:03:33,102][INFO ][plugins                  ] [master1] loaded [], sites []
[2015-01-12 16:03:36,249][INFO ][node                     ] [master1] initialized
[2015-01-12 16:03:36,249][INFO ][node                     ] [master1] starting ...
[2015-01-12 16:03:36,514][INFO ][transport                ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.2.101:9300]}
[2015-01-12 16:03:36,795][INFO ][discovery                ] [master1] local1/xBx3MDWZT--1dKhACi3KSA
[2015-01-12 16:03:39,844][INFO ][cluster.service          ] [master1] new_master [master1][xBx3MDWZT--1dKhACi3KSA][dell13][inet[/192.168.2.101:9300]]{master=true}, reason: zen-disco-join (elected_as_master)
[2015-01-12 16:03:39,901][INFO ][http                     ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.2.101:9200]}
[2015-01-12 16:03:39,901][INFO ][node                     ] [master1] started
[2015-01-12 16:03:39,964][INFO ][gateway                  ] [master1] recovered [0] indices into cluster_state
[2015-01-12 16:04:09,878][DEBUG][action.admin.cluster.node.stats] [master1] failed to execute on node [xBx3MDWZT--1dKhACi3KSA]
java.lang.IllegalStateException: Free bytes [-1] cannot be less than 0 or greater than total bytes [-1]
	at org.elasticsearch.cluster.DiskUsage.<init>(DiskUsage.java:32)
	at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:279)
	at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:260)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.finishHim(TransportNodesOperationAction.java:221)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.onOperation(TransportNodesOperationAction.java:196)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$900(TransportNodesOperationAction.java:96)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$2.run(TransportNodesOperationAction.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by tlrx** [comment]
Thanks for reporting @dobariya 

You should report this on elasticsearch github repository  https://github.com/elasticsearch/elasticsearch/issues because this repository concerns the cloud-aws plugin.
